# Generated by Django 4.2.11 on 2025-12-12 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_instructor_options_alter_student_options_and_more'),
        ('courses', '0006_alter_category_options_alter_course_options_and_more'),
        ('divisions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_page',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الصفحة المستهدفة'),
        ),
        migrations.CreateModel(
            name='BannerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('notification_type', models.CharField(choices=[('banner_top', 'بانر أعلى الموقع'), ('banner_dashboard_student', 'بانر داشبورد الطلاب'), ('banner_dashboard_instructor', 'بانر داشبورد المعلمين')], default='banner_top', max_length=30, verbose_name='نوع البانر')),
                ('target_pages', models.JSONField(default=list, help_text='قائمة بصفحات المستهدفة، مثال: ["home", "my-courses"]', verbose_name='الصفحات المستهدفة')),
                ('text_color', models.CharField(default='#000000', help_text='صيغة HEX مثل #000000', max_length=7, verbose_name='لون النص')),
                ('background_color', models.CharField(default='#FFFFFF', help_text='صيغة HEX مثل #FFFFFF', max_length=7, verbose_name='لون الخلفية')),
                ('target_type', models.CharField(choices=[('all_students', 'جميع الطلاب'), ('specific_students', 'طلاب محددين'), ('specific_divisions', 'شعب محددة'), ('all_instructors', 'جميع المعلمين'), ('specific_instructors', 'معلمين محددين'), ('all_users', 'جميع المستخدمين')], default='all_users', max_length=30, verbose_name='نوع الاستهداف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('send_email', models.BooleanField(default=False, verbose_name='إرسال عبر البريد الإلكتروني')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_banner_notifications', to=settings.AUTH_USER_MODEL, verbose_name='منشئ الإشعار')),
                ('target_divisions', models.ManyToManyField(blank=True, related_name='banner_notifications', to='divisions.division', verbose_name='الشعب المستهدفة')),
                ('target_instructors', models.ManyToManyField(blank=True, related_name='banner_notifications', to='users.instructor', verbose_name='المعلمين المستهدفون')),
                ('target_students', models.ManyToManyField(blank=True, related_name='banner_notifications', to='users.student', verbose_name='الطلاب المستهدفون')),
            ],
            options={
                'verbose_name': 'إشعار بانر',
                'verbose_name_plural': 'إشعارات البانر',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendancePenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_absences', models.PositiveIntegerField(help_text='عند الوصول لهذا العدد يتم إرسال إشعار الحرمان', verbose_name='عدد الغيابات المسموح بها')),
                ('warning_threshold', models.PositiveIntegerField(blank=True, help_text='عند الوصول لهذا العدد يتم إرسال تحذير (اختياري)', null=True, verbose_name='عدد الغيابات للتحذير')),
                ('penalty_message', models.TextField(help_text='الرسالة التي يتم إرسالها للطالب عند الوصول للحد الأقصى', verbose_name='رسالة الحرمان')),
                ('warning_message', models.TextField(blank=True, help_text='الرسالة التي يتم إرسالها عند الوصول لعدد التحذير', null=True, verbose_name='رسالة التحذير')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('course', models.ForeignKey(blank=True, help_text='إذا ترك فارغاً، ينطبق على جميع الدورات', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_penalties', to='courses.course', verbose_name='الدورة')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_penalties', to='users.instructor', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'قاعدة حرمان',
                'verbose_name_plural': 'قواعد الحرمان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='banner_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.bannernotification', verbose_name='إشعار البانر'),
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absences_count', models.PositiveIntegerField(default=0, verbose_name='عدد الغيابات')),
                ('last_absence_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر غياب')),
                ('penalty_sent', models.BooleanField(default=False, verbose_name='تم إرسال إشعار الحرمان')),
                ('warning_sent', models.BooleanField(default=False, verbose_name='تم إرسال إشعار التحذير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='courses.course', verbose_name='الدورة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'سجل حضور الطالب',
                'verbose_name_plural': 'سجلات حضور الطلاب',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['student', 'course'], name='notificatio_student_3f12e8_idx'), models.Index(fields=['absences_count'], name='notificatio_absence_b63f3a_idx')],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AddIndex(
            model_name='bannernotification',
            index=models.Index(fields=['is_active', 'notification_type'], name='notificatio_is_acti_764544_idx'),
        ),
        migrations.AddIndex(
            model_name='bannernotification',
            index=models.Index(fields=['start_date', 'end_date'], name='notificatio_start_d_790454_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancepenalty',
            unique_together={('instructor', 'course', 'max_absences')},
        ),
    ]
