# Generated by Django 4.2.11 on 2025-12-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_target_page_bannernotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannernotification',
            name='send_immediately',
            field=models.BooleanField(default=True, help_text='إرسال الإشعار فوراً بعد الحفظ (حتى لو كان مجدولاً)', verbose_name='إرسال فوري'),
        ),
    ]
