# Generated by Django 4.2.11 on 2025-12-11 23:48

import content.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_alter_category_options_alter_course_options_and_more'),
        ('content', '0003_alter_lessonresource_metadata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'درس', 'verbose_name_plural': 'دروس'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'وحدة', 'verbose_name_plural': 'وحدات'},
        ),
        migrations.AlterModelOptions(
            name='userprogress',
            options={'ordering': ['-last_accessed'], 'verbose_name': 'تقدم المستخدم', 'verbose_name_plural': 'تقدم المستخدمين'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, help_text='المحتوى الرئيسي للدرس (HTML/نص)', null=True, verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, help_text='وصف مختصر للدرس', null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم')], default='beginner', help_text='مستوى صعوبة الدرس', max_length=20, verbose_name='مستوى الصعوبة'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='الوقت المقدر للإكمال بالدقائق', validators=[django.core.validators.MinValueValidator(0, message='المدة لا يمكن أن تكون سالبة'), django.core.validators.MaxValueValidator(1440, message='المدة لا يمكن أن تكون أكثر من 24 ساعة')], verbose_name='المدة بالدقائق'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(default=True, help_text='يحدد ما إذا كان هذا الدرس يجب أن يعامل كنشط', verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_free',
            field=models.BooleanField(default=False, help_text='يحدد ما إذا كان هذا الدرس متاحاً مجاناً', verbose_name='مجاني'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'فيديو'), ('article', 'مقال')], default='article', help_text='نوع الدرس', max_length=20, verbose_name='نوع الدرس'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.module', verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='الترتيب الذي يظهر به الدرس في الوحدة', verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='requires_completion',
            field=models.BooleanField(default=True, help_text='إذا كان True، يجب على المستخدم إكمال هذا الدرس للمتابعة إلى التالي', verbose_name='يتطلب الإكمال'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='resources',
            field=models.ManyToManyField(blank=True, help_text='موارد إضافية لهذا الدرس', related_name='lessons', to='content.lessonresource', verbose_name='الموارد'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, help_text='تسمية قصيرة تحتوي فقط على أحرف وأرقام وشرطات سفلية أو شرطات للروابط', max_length=250, unique=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(help_text='عنوان الدرس', max_length=200, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='رابط محتوى الفيديو (إن وجد)', null=True, verbose_name='رابط الفيديو'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='الدورة'),
        ),
        migrations.AlterField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, help_text='وصف تفصيلي للوحدة', null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(default=True, help_text='يحدد ما إذا كانت هذه الوحدة يجب أن تعامل كنشطة', verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(help_text='اسم الوحدة', max_length=2000, verbose_name='اسم الوحدة'),
        ),
        migrations.AlterField(
            model_name='module',
            name='note',
            field=models.TextField(blank=True, help_text='ملاحظات خاصة للمدربين', null=True, verbose_name='ملاحظات المدرب'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='الترتيب الذي تظهر به الوحدة في الدورة', verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='module',
            name='pdf',
            field=models.FileField(blank=True, help_text='رفع ملف PDF (حد أقصى 100MB)', null=True, upload_to=content.models.module_pdf_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), content.models.validate_file_size], verbose_name='ملف PDF'),
        ),
        migrations.AlterField(
            model_name='module',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='الوحدات التي يجب إكمالها قبل هذه الوحدة', related_name='is_prerequisite_for', to='content.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر'),
        ),
        migrations.AlterField(
            model_name='module',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('archived', 'مؤرشف')], default='draft', help_text='حالة نشر الوحدة', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='module',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='module',
            name='video',
            field=models.FileField(blank=True, help_text='رفع ملف فيديو (حد أقصى 100MB، MP4/WebM/MOV)', null=True, upload_to=content.models.module_video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov']), content.models.validate_file_size], verbose_name='ملف الفيديو'),
        ),
        migrations.AlterField(
            model_name='module',
            name='video_duration',
            field=models.PositiveIntegerField(default=0, help_text='مدة الفيديو بالثواني', verbose_name='مدة الفيديو بالثواني'),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'لم يبدأ'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل')], default='not_started', help_text='Current status of the module progress', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='عندما أكمل المستخدم الدورة', null=True, verbose_name='تاريخ الإكمال'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.course', verbose_name='الدورة'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, help_text='عندما سجل المستخدم في الدورة', verbose_name='تاريخ التسجيل'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True, help_text='عندما وصل المستخدم آخر مرة للدورة', verbose_name='آخر وصول'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='last_lesson_completed',
            field=models.ForeignKey(blank=True, help_text='آخر درس أكمل المستخدم', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.lesson', verbose_name='آخر درس مكتمل'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='notes',
            field=models.TextField(blank=True, help_text='ملاحظات المستخدم لهذه الدورة', null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='overall_progress',
            field=models.FloatField(default=0, help_text='نسبة التقدم الإجمالية (0-100)', validators=[django.core.validators.MinValueValidator(0, message='التقدم لا يمكن أن يكون سالباً'), django.core.validators.MaxValueValidator(100, message='التقدم لا يمكن أن يتجاوز 100%')], verbose_name='التقدم الإجمالي'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='عندما وصل المستخدم أول مرة لمحتوى الدورة', null=True, verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'لم يبدأ'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل')], default='not_started', help_text='الحالة الحالية للمستخدم في هذه الدورة', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='time_spent_minutes',
            field=models.PositiveIntegerField(default=0, help_text='إجمالي الوقت المستغرق على الدورة بالدقائق', verbose_name='الوقت المستغرق (بالدقائق)'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
