# Generated by Django 4.2.11 on 2025-12-11 23:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_alter_category_options_alter_course_options_and_more'),
        ('reviews', '0002_reviewlike_coursereview_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursereview',
            options={'ordering': ['-created_at'], 'verbose_name': 'تقييم دورة', 'verbose_name_plural': 'تقييمات الدورات'},
        ),
        migrations.AlterModelOptions(
            name='reviewreply',
            options={'ordering': ['created_at'], 'verbose_name': 'رد على التقييم', 'verbose_name_plural': 'ردود التقييمات'},
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course', verbose_name='الدورة'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='موافق عليه'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='likes',
            field=models.ManyToManyField(related_name='liked_reviews', through='reviews.ReviewLike', to=settings.AUTH_USER_MODEL, verbose_name='الإعجابات'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 - ضعيف'), (2, '2 - مقبول'), (3, '3 - جيد'), (4, '4 - جيد جداً'), (5, '5 - ممتاز')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='review_text',
            field=models.TextField(blank=True, null=True, verbose_name='نص التقييم'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='reviewreply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='reviewreply',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='موافق عليه'),
        ),
        migrations.AlterField(
            model_name='reviewreply',
            name='reply_text',
            field=models.TextField(verbose_name='نص الرد'),
        ),
        migrations.AlterField(
            model_name='reviewreply',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.coursereview', verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='reviewreply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='reviewreply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_replies', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
