# Generated by Django 4.2.11 on 2025-12-11 23:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_alter_instructor_options_alter_student_options_and_more'),
        ('courses', '0005_remove_course_language_alter_course_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'فئة', 'verbose_name_plural': 'فئات'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'permissions': [('can_publish_course', 'Can publish course'), ('can_edit_all_courses', 'Can edit all courses'), ('can_view_analytics', 'Can view course analytics')], 'verbose_name': 'دورة', 'verbose_name_plural': 'دورات'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrollment_date'], 'verbose_name': 'تسجيل', 'verbose_name_plural': 'التسجيلات'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_default',
            field=models.BooleanField(default=False, help_text='لا يمكن حذف الفئات الافتراضية', verbose_name='فئة افتراضية'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='course',
            name='average_rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='التقييم المتوسط'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category', verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='course',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر الخصم'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images/', verbose_name='صورة الدورة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(related_name='courses_taught', to='users.instructor', verbose_name='المدربون'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_certified',
            field=models.BooleanField(default=False, verbose_name='يقدم شهادة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_complete_course',
            field=models.BooleanField(default=True, help_text='حدد إذا كانت هذه دورة كاملة بمحتوى كامل. ألغِ التحديد إذا كانت مجرد إعلان/معاينة للدورة.', verbose_name='دورة كاملة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='مميز'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='مجاني'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True, verbose_name='مستوى الصعوبة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='materials_pdf',
            field=models.FileField(blank=True, help_text='رفع مواد إضافية للدورة PDF', null=True, upload_to='courses/materials/', verbose_name='مواد الدورة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف SEO'),
        ),
        migrations.AlterField(
            model_name='course',
            name='meta_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان SEO'),
        ),
        migrations.AlterField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='users.organization', verbose_name='المنظمة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='course',
            name='promotional_video',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الفيديو الترويجي'),
        ),
        migrations.AlterField(
            model_name='course',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف المختصر'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_courses', through='courses.Enrollment', to=settings.AUTH_USER_MODEL, verbose_name='الطلاب'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان الفرعي'),
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus_pdf',
            field=models.FileField(blank=True, help_text='رفع ملف المنهج الدراسي PDF', null=True, upload_to='courses/syllabus/', verbose_name='ملف المنهج PDF'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.tag', verbose_name='الوسوم'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, default='دورة بدون عنوان', max_length=200, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_enrollments',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي التسجيلات'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='الدورة'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='مدفوع'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر وصول'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مبلغ الدفع'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='progress',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='التقدم %'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('suspended', 'Suspended')], default='active', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رقم المعاملة'),
        ),
    ]
