# Generated by Django 4.2.11 on 2025-12-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_instructor_options_alter_student_options_and_more'),
        ('courses', '0006_alter_category_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='courses_taught', to='users.instructor', verbose_name='المدربون'),
        ),
    ]
