# Generated by Django 4.2.11 on 2025-12-09 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0003_alter_exam_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='graded_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ تعديل الدرجة', null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='graded_by',
            field=models.ForeignKey(blank=True, help_text='المدرس الذي عدل الدرجة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='is_grade_visible',
            field=models.BooleanField(default=False, help_text='هل الدرجة ظاهرة للطالب؟'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='is_manually_graded',
            field=models.BooleanField(default=False, help_text='هل تم تعديل الدرجة يدوياً؟'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='manual_grade',
            field=models.FloatField(blank=True, help_text='الدرجة المعدلة يدوياً من المدرس', null=True),
        ),
        migrations.AddField(
            model_name='userexamattempt',
            name='graded_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ تعديل الدرجة', null=True),
        ),
        migrations.AddField(
            model_name='userexamattempt',
            name='graded_by',
            field=models.ForeignKey(blank=True, help_text='المدرس الذي عدل الدرجة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_exam_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userexamattempt',
            name='is_grade_visible',
            field=models.BooleanField(default=False, help_text='هل الدرجة ظاهرة للطالب؟'),
        ),
        migrations.AddField(
            model_name='userexamattempt',
            name='is_manually_graded',
            field=models.BooleanField(default=False, help_text='هل تم تعديل الدرجة يدوياً؟'),
        ),
        migrations.AddField(
            model_name='userexamattempt',
            name='manual_grade',
            field=models.FloatField(blank=True, help_text='الدرجة المعدلة يدوياً من المدرس', null=True),
        ),
    ]
