# Generated by Django 4.2.11 on 2025-12-11 23:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_lesson_options_alter_module_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_alter_category_options_alter_course_options_and_more'),
        ('assignments', '0004_quizattempt_graded_at_quizattempt_graded_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['order'], 'verbose_name': 'إجابة', 'verbose_name_plural': 'إجابات'},
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_at'], 'verbose_name': 'واجب', 'verbose_name_plural': 'واجبات'},
        ),
        migrations.AlterModelOptions(
            name='assignmentanswer',
            options={'ordering': ['order'], 'verbose_name': 'إجابة واجب', 'verbose_name_plural': 'إجابات الواجبات'},
        ),
        migrations.AlterModelOptions(
            name='assignmentquestion',
            options={'ordering': ['order'], 'verbose_name': 'سؤال واجب', 'verbose_name_plural': 'أسئلة الواجبات'},
        ),
        migrations.AlterModelOptions(
            name='assignmentquestionresponse',
            options={'verbose_name': 'إجابة سؤال واجب', 'verbose_name_plural': 'إجابات أسئلة الواجبات'},
        ),
        migrations.AlterModelOptions(
            name='assignmentsubmission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'تسليم واجب', 'verbose_name_plural': 'تسليمات الواجبات'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'امتحان', 'verbose_name_plural': 'امتحانات'},
        ),
        migrations.AlterModelOptions(
            name='examanswer',
            options={'ordering': ['order'], 'verbose_name': 'إجابة امتحان', 'verbose_name_plural': 'إجابات الامتحان'},
        ),
        migrations.AlterModelOptions(
            name='examquestion',
            options={'ordering': ['order'], 'verbose_name': 'سؤال امتحان', 'verbose_name_plural': 'أسئلة الامتحان'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'سؤال', 'verbose_name_plural': 'أسئلة'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'كويز', 'verbose_name_plural': 'كويزات'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'verbose_name': 'محاولة كويز', 'verbose_name_plural': 'محاولات الكويز'},
        ),
        migrations.AlterModelOptions(
            name='quizuseranswer',
            options={'verbose_name': 'إجابة كويز', 'verbose_name_plural': 'إجابات الكويز'},
        ),
        migrations.AlterModelOptions(
            name='userexamanswer',
            options={'verbose_name': 'إجابة امتحان', 'verbose_name_plural': 'إجابات الامتحان'},
        ),
        migrations.AlterModelOptions(
            name='userexamattempt',
            options={'verbose_name': 'محاولة امتحان', 'verbose_name_plural': 'محاولات الامتحان'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='الشرح'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='صحيحة'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assignments.question', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='نص الإجابة'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='allow_late_submissions',
            field=models.BooleanField(default=False, verbose_name='السماح بالتسليم المتأخر'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(blank=True, help_text='ملف الواجب المرفق', null=True, upload_to='assignment_files/', verbose_name='ملف الواجب'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course', verbose_name='الدورة'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(verbose_name='تاريخ الاستحقاق'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='has_file_upload',
            field=models.BooleanField(default=False, help_text='هل يسمح برفع ملفات؟', verbose_name='يسمح برفع ملفات'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='has_questions',
            field=models.BooleanField(default=False, help_text='هل يحتوي الواجب على أسئلة؟', verbose_name='يحتوي على أسئلة'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='late_submission_penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='عقوبة التسليم المتأخر'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='content.module', verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='points',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='النقاط'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=200, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='assignmentanswer',
            name='explanation',
            field=models.TextField(blank=True, help_text='شرح الإجابة', null=True, verbose_name='الشرح'),
        ),
        migrations.AlterField(
            model_name='assignmentanswer',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='هل هذه الإجابة صحيحة؟', verbose_name='صحيحة'),
        ),
        migrations.AlterField(
            model_name='assignmentanswer',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='ترتيب الإجابة', verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='assignmentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assignments.assignmentquestion', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='assignmentanswer',
            name='text',
            field=models.CharField(help_text='نص الإجابة', max_length=1000, verbose_name='نص الإجابة'),
        ),
        migrations.AlterField(
            model_name='assignmentquestion',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.assignment', verbose_name='الواجب'),
        ),
        migrations.AlterField(
            model_name='assignmentquestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='شرح السؤال أو الإجابة النموذجية', null=True, verbose_name='الشرح'),
        ),
        migrations.AlterField(
            model_name='assignmentquestion',
            name='image',
            field=models.ImageField(blank=True, help_text='صورة توضيحية للسؤال', null=True, upload_to='assignment_question_images/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='assignmentquestion',
            name='is_required',
            field=models.BooleanField(default=True, help_text='هل السؤال إجباري؟', verbose_name='إجباري'),
        ),
        migrations.AlterField(
            model_name='assignmentquestion',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='ترتيب السؤال', verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='assignmentquestion',
            name='points',
            field=models.PositiveIntegerField(default=1, help_text='الدرجة المخصصة لهذا السؤال', verbose_name='النقاط'),
        ),
        migrations.AlterField(
            model_name='assignmentquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'اختيار من متعدد'), ('true_false', 'صح أو خطأ'), ('short_answer', 'إجابة قصيرة'), ('essay', 'مقال'), ('file_upload', 'رفع ملف')], default='essay', max_length=20, verbose_name='نوع السؤال'),
        ),
        migrations.AlterField(
            model_name='assignmentquestion',
            name='text',
            field=models.TextField(help_text='نص السؤال', verbose_name='نص السؤال'),
        ),
        migrations.AlterField(
            model_name='assignmentquestionresponse',
            name='feedback',
            field=models.TextField(blank=True, help_text='ملاحظات المدرس على الإجابة', verbose_name='التعليقات'),
        ),
        migrations.AlterField(
            model_name='assignmentquestionresponse',
            name='file_answer',
            field=models.FileField(blank=True, help_text='الملف المرفوع كإجابة', null=True, upload_to='assignment_question_files/', verbose_name='الملف المرفوع'),
        ),
        migrations.AlterField(
            model_name='assignmentquestionresponse',
            name='points_earned',
            field=models.FloatField(default=0, help_text='الدرجة المكتسبة', verbose_name='الدرجة المكتسبة'),
        ),
        migrations.AlterField(
            model_name='assignmentquestionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignmentquestion', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='assignmentquestionresponse',
            name='selected_answer',
            field=models.ForeignKey(blank=True, help_text='الإجابة المختارة', null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.assignmentanswer', verbose_name='الإجابة المختارة'),
        ),
        migrations.AlterField(
            model_name='assignmentquestionresponse',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='assignments.assignmentsubmission', verbose_name='التسليم'),
        ),
        migrations.AlterField(
            model_name='assignmentquestionresponse',
            name='text_answer',
            field=models.TextField(blank=True, help_text='الإجابة النصية', null=True, verbose_name='الإجابة النصية'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment', verbose_name='الواجب'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='التعليقات'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التقييم'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_assignments', to=settings.AUTH_USER_MODEL, verbose_name='معدل بواسطة'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='is_late',
            field=models.BooleanField(default=False, verbose_name='متأخر'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'مُرسل'), ('graded', 'مُقيم'), ('returned', 'مُعاد للمراجعة')], default='submitted', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submission_text',
            field=models.TextField(blank=True, help_text='النص المكتوب للإجابة', verbose_name='نص التسليم'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسليم'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submitted_file',
            field=models.FileField(blank=True, help_text='الملف المرفوع', null=True, upload_to='assignment_submissions/', verbose_name='الملف المرفوع'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='allow_multiple_attempts',
            field=models.BooleanField(default=False, verbose_name='السماح بمحاولات متعددة'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course', verbose_name='الدورة'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_final',
            field=models.BooleanField(default=False, help_text='هل هذا امتحان نهائي للدورة؟', verbose_name='امتحان نهائي'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1, verbose_name='الحد الأقصى للمحاولات'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_exams', to='content.module', verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='pass_mark',
            field=models.FloatField(default=60.0, help_text='النسبة المئوية للنجاح', verbose_name='علامة النجاح'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='randomize_questions',
            field=models.BooleanField(default=False, verbose_name='ترتيب الأسئلة عشوائياً'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='show_answers_after',
            field=models.BooleanField(default=False, help_text='إظهار الإجابات الصحيحة بعد الانتهاء', verbose_name='إظهار الإجابات بعد الانتهاء'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, help_text='وقت الامتحان بالدقائق', null=True, verbose_name='الحد الزمني'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=255, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_points',
            field=models.PositiveIntegerField(default=100, verbose_name='إجمالي النقاط'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='الشرح'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='صحيحة'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assignments.examquestion', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='نص الإجابة'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.exam', verbose_name='الامتحان'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='شرح الإجابة الصحيحة', null=True, verbose_name='الشرح'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exam_question_images/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='points',
            field=models.PositiveIntegerField(default=1, verbose_name='النقاط'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'اختيار من متعدد'), ('true_false', 'صح أو خطأ'), ('short_answer', 'إجابة قصيرة')], default='multiple_choice', max_length=20, verbose_name='نوع السؤال'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='text',
            field=models.TextField(verbose_name='نص السؤال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='شرح الإجابة الصحيحة', null=True, verbose_name='الشرح'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1, verbose_name='النقاط'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'اختيار من متعدد'), ('true_false', 'صح أو خطأ'), ('short_answer', 'إجابة قصيرة')], default='multiple_choice', max_length=20, verbose_name='نوع السؤال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.quiz', verbose_name='الكويز'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='نص السؤال'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_quizzes', to='courses.course', verbose_name='الدورة'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_quizzes', to='content.module', verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pass_mark',
            field=models.FloatField(default=0, verbose_name='علامة النجاح'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('video', 'فيديو كويز'), ('module', 'كويز وحدة'), ('quick', 'كويز سريع')], default='video', max_length=20, verbose_name='نوع الكويز'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='وقت البدء'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, help_text='الحد الزمني بالدقائق', null=True, verbose_name='الحد الزمني'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1, verbose_name='رقم المحاولة'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='graded_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ تعديل الدرجة', null=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='graded_by',
            field=models.ForeignKey(blank=True, help_text='المدرس الذي عدل الدرجة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='معدل بواسطة'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='is_grade_visible',
            field=models.BooleanField(default=False, help_text='هل الدرجة ظاهرة للطالب؟', verbose_name='الدرجة ظاهرة'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='is_manually_graded',
            field=models.BooleanField(default=False, help_text='هل تم تعديل الدرجة يدوياً؟', verbose_name='معدل يدوياً'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='manual_grade',
            field=models.FloatField(blank=True, help_text='الدرجة المعدلة يدوياً من المدرس', null=True, verbose_name='الدرجة المعدلة يدوياً'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='passed',
            field=models.BooleanField(blank=True, null=True, verbose_name='ناجح'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assignments.quiz', verbose_name='الكويز'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='النتيجة'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت البدء'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='quizuseranswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assignments.quizattempt', verbose_name='المحاولة'),
        ),
        migrations.AlterField(
            model_name='quizuseranswer',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True, verbose_name='صحيحة'),
        ),
        migrations.AlterField(
            model_name='quizuseranswer',
            name='points_earned',
            field=models.FloatField(default=0, verbose_name='النقاط المكتسبة'),
        ),
        migrations.AlterField(
            model_name='quizuseranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.question', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='quizuseranswer',
            name='selected_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.answer', verbose_name='الإجابة المختارة'),
        ),
        migrations.AlterField(
            model_name='quizuseranswer',
            name='text_answer',
            field=models.TextField(blank=True, null=True, verbose_name='الإجابة النصية'),
        ),
        migrations.AlterField(
            model_name='userexamanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assignments.userexamattempt', verbose_name='المحاولة'),
        ),
        migrations.AlterField(
            model_name='userexamanswer',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True, verbose_name='صحيحة'),
        ),
        migrations.AlterField(
            model_name='userexamanswer',
            name='points_earned',
            field=models.FloatField(default=0, verbose_name='النقاط المكتسبة'),
        ),
        migrations.AlterField(
            model_name='userexamanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.examquestion', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='userexamanswer',
            name='selected_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.examanswer', verbose_name='الإجابة المختارة'),
        ),
        migrations.AlterField(
            model_name='userexamanswer',
            name='text_answer',
            field=models.TextField(blank=True, null=True, verbose_name='الإجابة النصية'),
        ),
        migrations.AlterField(
            model_name='userexamattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1, verbose_name='رقم المحاولة'),
        ),
        migrations.AlterField(
            model_name='userexamattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء'),
        ),
        migrations.AlterField(
            model_name='userexamattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assignments.exam', verbose_name='الامتحان'),
        ),
        migrations.AlterField(
            model_name='userexamattempt',
            name='graded_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ تعديل الدرجة', null=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='userexamattempt',
            name='graded_by',
            field=models.ForeignKey(blank=True, help_text='المدرس الذي عدل الدرجة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='معدل بواسطة'),
        ),
        migrations.AlterField(
            model_name='userexamattempt',
            name='is_grade_visible',
            field=models.BooleanField(default=False, help_text='هل الدرجة ظاهرة للطالب؟', verbose_name='الدرجة ظاهرة'),
        ),
        migrations.AlterField(
            model_name='userexamattempt',
            name='is_manually_graded',
            field=models.BooleanField(default=False, help_text='هل تم تعديل الدرجة يدوياً؟', verbose_name='معدل يدوياً'),
        ),
        migrations.AlterField(
            model_name='userexamattempt',
            name='manual_grade',
            field=models.FloatField(blank=True, help_text='الدرجة المعدلة يدوياً من المدرس', null=True, verbose_name='الدرجة المعدلة يدوياً'),
        ),
        migrations.AlterField(
            model_name='userexamattempt',
            name='passed',
            field=models.BooleanField(blank=True, null=True, verbose_name='ناجح'),
        ),
        migrations.AlterField(
            model_name='userexamattempt',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='النتيجة'),
        ),
        migrations.AlterField(
            model_name='userexamattempt',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت البدء'),
        ),
        migrations.AlterField(
            model_name='userexamattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
