# Generated by Django 5.0 on 2025-10-15 01:28

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='المحتوى')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='circulars/attachments/', verbose_name='مرفق')),
                ('send_email', models.BooleanField(default=False, verbose_name='إرسال بريد')),
                ('send_notification', models.BooleanField(default=True, verbose_name='إرسال إشعار')),
                ('show_on_homepage', models.BooleanField(default=True, verbose_name='عرض في الصفحة الرئيسية')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('scheduled', 'مجدول'), ('sent', 'مرسل')], default='draft', max_length=20, verbose_name='الحالة')),
                ('publish_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت النشر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_circulars', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
            ],
            options={
                'verbose_name': 'تعميم',
                'verbose_name_plural': 'التعاميم',
                'ordering': ['-created_at'],
            },
        ),
    ]
