# Generated by Django 5.0 on 2025-10-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circulars', '0001_initial'),
        ('divisions', '0001_initial'),
        ('users', '0006_alter_instructor_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circular',
            name='target_divisions',
            field=models.ManyToManyField(blank=True, related_name='circulars', to='divisions.division', verbose_name='الشعب المستهدفة'),
        ),
        migrations.AddField(
            model_name='circular',
            name='target_students',
            field=models.ManyToManyField(blank=True, related_name='circulars', to='users.student', verbose_name='الطلاب المستهدفون'),
        ),
    ]
