# Generated by Django 4.2.11 on 2025-12-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_is_archived_archiveduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Student', 'Student'), ('DiplomaStudent', 'طالب الدبلوم'), ('Instructor', 'Instructor'), ('Teacher', 'المدرس (المنظمة)'), ('Organization', 'Organization'), ('CustomerService', 'خدمة عملاء'), ('CertificateStaff', 'موظفين شهادات')], default='Student', max_length=2000, null=True),
        ),
    ]
