# Generated by Django 4.2.11 on 2025-12-09 05:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_language_alter_course_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_alter_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4.0)], verbose_name='GPA')),
                ('semester', models.CharField(blank=True, max_length=50, null=True, verbose_name='الفصل الدراسي')),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True, verbose_name='السنة الأكاديمية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_gpas', to='courses.course', verbose_name='الكورس')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gpas', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpa_records', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'GPA الطالب',
                'verbose_name_plural': 'GPA الطلاب',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'course', 'semester', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='GPAHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='GPA السابق')),
                ('new_gpa', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='GPA الجديد')),
                ('change_reason', models.TextField(blank=True, null=True, verbose_name='سبب التغيير')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التغيير')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gpa_changes', to=settings.AUTH_USER_MODEL, verbose_name='تم التغيير بواسطة')),
                ('gpa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='users.studentgpa', verbose_name='GPA')),
            ],
            options={
                'verbose_name': 'سجل GPA',
                'verbose_name_plural': 'سجلات GPA',
                'ordering': ['-changed_at'],
            },
        ),
    ]
