# Generated by Django 4.2.11 on 2025-12-11 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_studentgpa_gpahistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgpa',
            options={'ordering': ['-created_at'], 'verbose_name': 'درجة الطالب', 'verbose_name_plural': 'درجات الطلاب'},
        ),
        migrations.AddField(
            model_name='studentgpa',
            name='cumulative_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='المعدل التراكمي'),
        ),
        migrations.AddField(
            model_name='studentgpa',
            name='gpa_scale',
            field=models.DecimalField(choices=[(4, '4'), (5, '5')], decimal_places=0, default=4, max_digits=2, verbose_name='أصل المعدل'),
        ),
        migrations.AddField(
            model_name='studentgpa',
            name='grade_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم الدرجة'),
        ),
        migrations.AddField(
            model_name='studentgpa',
            name='semester_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='المعدل الفصلي'),
        ),
        migrations.AlterField(
            model_name='studentgpa',
            name='gpa',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5.0)], verbose_name='الدرجة'),
        ),
    ]
