# Generated by Django 4.2.11 on 2025-12-11 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_studentgpa_options_studentgpa_cumulative_gpa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'مدرب', 'verbose_name_plural': 'مدربون'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'طالب', 'verbose_name_plural': 'طلاب'},
        ),
        migrations.AlterField(
            model_name='gpahistory',
            name='gpa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='users.studentgpa', verbose_name='الدرجة'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='مؤرشف'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='الملف الشخصي'),
        ),
    ]
