# Generated by Django 4.2.11 on 2025-12-22 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_instructor_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgpa',
            name='cumulative_gpa',
        ),
        migrations.RemoveField(
            model_name='studentgpa',
            name='gpa_scale',
        ),
        migrations.RemoveField(
            model_name='studentgpa',
            name='semester_gpa',
        ),
        migrations.AlterField(
            model_name='studentgpa',
            name='gpa',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الدرجة'),
        ),
    ]
