# Generated by Django 4.2.11 on 2025-12-22 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_gpa_scale_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgpa',
            options={'ordering': ['-created_at'], 'verbose_name': 'درجة الطالب', 'verbose_name_plural': 'درجات الطلاب'},
        ),
    ]
