# Generated by Django 4.2.11 on 2025-12-22 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_update_studentgpa_verbose_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gpahistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'سجل الدرجة', 'verbose_name_plural': 'سجل الدرجات'},
        ),
    ]
