# Generated by Django 5.0 on 2025-10-08 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_delete_presetcertificatetemplate_and_more'),
        ('courses', '0004_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course', verbose_name='الدورة'),
        ),
    ]
