# Generated by Django 5.0 on 2025-10-09 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_alter_certificate_course'),
        ('courses', '0004_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='duration_days',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='مدة الدورة بالأيام'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='تاريخ النهاية'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='end_date_hijri',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='تاريخ النهاية هجري'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='رقم الهوية'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='تاريخ البداية'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='start_date_hijri',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='تاريخ البداية هجري'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='certificate_text',
            field=models.TextField(default='يشهد مركز التطوير المهني للتدريب بأن المتدرب/ة\n({student_name})\nرقم الهوية: ({national_id})\n\nقد حضر(ت) برنامجًا تدريبيًا بعنوان\n{course_name}\n\nلمدة ({duration_days}) أيام بمعدل ({duration_hours}) ساعة تدريبية وذلك في الفترة من\n({start_date}) إلى ({end_date})\nالموافق ({start_date_hijri}) إلى ({end_date_hijri})\n\nوبناءً على ذلك تم منحه/ا الشهادة', help_text='يمكنك استخدام المتغيرات: {student_name}, {national_id}, {course_name}, {duration_days}, {duration_hours}, {start_date}, {end_date}, {start_date_hijri}, {end_date_hijri}, {institution_name}, {completion_date}', verbose_name='نص الشهادة'),
        ),
    ]
