# Generated by Django 4.2.11 on 2025-12-09 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_language_alter_course_level'),
        ('certificates', '0004_certificate_duration_days_certificate_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course', verbose_name='الدورة'),
            preserve_default=False,
        ),
    ]
