# Generated by Django 4.2.11 on 2025-12-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_alter_certificate_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/images/', verbose_name='صورة الشهادة'),
        ),
    ]
